[book]
title = "Rust 程序设计语言 简体中文版"
author = "Steve Klabnik 和 Carol Nichols，以及来自 Rust 社区的贡献（Rust 中文社区翻译）"
description = "Rust 程序设计语言 简体中文版"
language = "zh-cn"
version = "0.0.1"

[build-dir]
destination = "mdbook"

[output.html]
additional-css = ["ferris.css"]
additional-js = ["ferris.js"]

[output.epub]
additional-resources = ["img/ferris/does_not_compile.svg","img/ferris/not_desired_behavior.svg","img/ferris/panics.svg","img/ferris/unsafe.svg","img/trpl04-01.svg","img/trpl04-02.svg","img/trpl04-03.svg","img/trpl04-04.svg","img/trpl04-05.svg","img/trpl04-06.svg","img/trpl14-01.png","img/trpl14-02.png","img/trpl14-03.png","img/trpl14-04.png","img/trpl15-01.svg","img/trpl15-02.svg","img/trpl15-03.svg","img/trpl15-04.svg"]
